notifications:
  email: false
os: linux
language: python
python: 3.8
install:
# install binary packages
- travis_retry pip install --upgrade pip
- travis_retry pip install setuptools wheel
# install package
- travis_retry pip install -e .
# for tests:
- travis_retry pip install codecov coverage flake8
- pip freeze
script:
#- coverage run --source=ckanext setup.py test
#- coverage report -m
- flake8 ckanext
after_success:
- codecov
before_deploy:
#- python setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: "ci_dcor"
  password:
    secure: "sgmd58b39a261HpJFg3DX95AFqgYBC4gOKo1Ve+hnWoRsliL1LHD18bwMvlku80yn6THcUsBr25HBPQ8y2nwM/x1KWPhwbYfEIscq4rIbL1M7Vr7PGQ9RfPNhVLcM0cwOsUTINw+3eOboShCyuk5jg4k1H3D5IMJx7XYq2CU36HSywlAnDHqt++8nwIdgW5hGwRvjNrAT4xVxbrfW1h9XRLQo4lc0jT1xcUeyuvhPUoNtQD5VSEyGtUF2Z1DjKL515JTwaUmX1Mnl5d60alaTCMgLcMaK/Sms/zXb9WBlnBM9VsYei+azTV9OTvd6JCKwuajmo8nz3HnBSLHxLGMCahH1fRX/6IQGgi1KoHRzgbQllF+B9lkHyXUSFtqEs0HS7cqPX0MBmKccrsfyXmzqXSASxzDK49RIY/Pj2XWSgirf0v2DtovTwsb+D5Cer1Dq4GPM3s7gdkSwljUKUmSd33HSnMK1hvqM+EMufyLdzK2C2T7twBVPp/PynoOSu0xj2OtJ85L1Dao+hwrToUuqssqvr0puyJp8b7OCw8GuaJrvm4VfMcPYUm9fy+AzIh0jwxwdQ8mJNZC99/6gNka7W5Y+lCWlPaAOc0TNlcGoRqxw8xgh0A/UKAGKSZp86Wtea+d6eE86e/U8URKDXUUzQSF9tNQgVEKOPoTh6v1pAU="
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
