name: Checks

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install flake8 dependencies
      run: |
        # prerequisites
        python -m pip install --upgrade pip wheel
        python -m pip install flake8
    - name: Lint with flake8
      run: |
        flake8 .
  dcor-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup vagrant vm
        run: |
          vagrant up
      - name: Run tests
        run: |
          vagrant ssh -- sudo bash /testing/vagrant-run-tests.sh
