name: Checks

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install flake8 dependencies
      run: |
        # prerequisites
        python -m pip install --upgrade pip wheel
        python -m pip install flake8
    - name: Lint with flake8
      run: |
        flake8 .
  dcor-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      # macOS sometimes allows symlinks to have permissions other than 777,
      # so change all symlink perms to match the Linux convention. Otherwise
      # the rsync run by Vagrant will complain that it can't copy over the
      # perms.
      - name: Fix symlink permissions
        run: find . -type link -exec chmod -h 777 \{\} \;
      - name: Setup vagrant vm
        run: |
          vagrant init paulmueller/dcor-test
          vagrant up
      - name: Run tests
        run: |
          vagrant ssh
          rsync /vagrant/ /project
          export CKAN_INI=/etc/ckan/default/test-dcor.ini
          cd /project
          pip install -e .
          py.test --disable-warnings ckanext
