name: Checks

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install flake8 dependencies
      run: |
        # prerequisites
        python -m pip install --upgrade pip wheel
        python -m pip install flake8
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Install testing dependencies
      run: |
        sudo apt install -y vagrant virtualbox ssh qemu-system-x86
    - name: Run tests with vagrant dcor-test image
      run: |
        vagrant init paulmueller/dcor-test
        vagrant ssh
        rsync /vagrant/ /project
        export CKAN_INI=/etc/ckan/default/test-dcor.ini
        cd /project
        pip install -e .
        py.test --disable-warnings ckanext
